apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: 80
