apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-tls
  namespace: gitlab
spec:
  entryPoints:
    - websecure 
  tls:
    secretName: cuiliangblog-tls
  routes:
    - match: Host(`gitlab.cuiliangblog.cn`)
      kind: Rule
      services:
        - name: gitlab-svc
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab
  namespace: gitlab
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`gitlab.cuiliangblog.cn`)
      kind: Rule
      services:
        - name: gitlab-svc
          port: 80