apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: http://gitlab.cuiliangblog.cn/devops/gitops-applicationSet.git
      revision: HEAD
      directories:
      - path: applications/* # 扫描路径
  template:      
    metadata:
      name: '{{.path.basename}}' # 组名（infra、model）
    spec:
      project: '{{.path.basename}}'
      source:
        repoURL: http://gitlab.cuiliangblog.cn/devops/gitops-applicationSet.git
        targetRevision: HEAD
        path: '{{.path.path}}'  # 完整的路径(application-set/myapps/prod或test)
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd 
      syncPolicy:
        automated:                               # 启用自动同步
          prune: true                            # 自动删除 Git 中已移除的资源
          selfHeal: true                         # 自动修复偏离集群状态的资源