apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: infra
        project: infra
      - name: model
        project: model
  # - git:
  #     repoURL: http://gitlab.cuiliangblog.cn/devops/gitops-applicationSet.git
  #     revision: HEAD
  #     directories:
  #     - path: application/* # 扫描路径
  template:      
    metadata:
      name: '{{ project }}-111' # 目录名称（prod,test）
    spec:
      project: '{{ project }}'
      source:
        repoURL: http://gitlab.cuiliangblog.cn/devops/gitops-applicationSet.git
        targetRevision: HEAD
        path: 'applications/{{ project }}'  # 完整的路径(application-set/myapps/prod或test)
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd # 目录名称
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
          - ServerSideApply=true